competences_single = ["sql", "excel", "python", "r",
                      "tableau", "powerbi", "datavisualisation", "dataviz",
                      "statistiques",
                      "ml",
                      "hadoop", "spark",  "sas", "matlab",
                      "bi",                 
                      "problem-solving",
                      "teamwork", "scrum", "agile",              
                      "decision-making",
                      "anglais", "communication", 
                      "adaptabilité", "adaptability",
                      "pandas", "numpy", "matplotlib", "seaborn", "scipy", "scikit-learn", "sklearn", "statsmodels",
                      "plotly", "bokeh", "beautifulsoup", "bs4", "requests", "tensorflow", "keras", "pytorch",
                      "mysql", "postgresql", "mongodb", "redis", "sqlite",
                      "oracle", "docker", "kubernetes", "mage", "airflow",
                      "jupyter", "apache kafka", "git", "github", "gitlab",
                      "aws",  "gcp", 
                      "nlp", "nltk", "spacy", "gensim", "word2vec", "bert", "gpt",              
                      "ner",  "tokenization", "tf-idf",
                      "modélisation",
                      "requêtage",
                      "bo", "qliksense",
                      "efficace", "autonome"
                      ]

competences_multi = ["power bi",
                     "visualisation de données",
                     "analyse statistique",
                     "apprentissage automatique",
                     "machine learning",
                     "nettoyage de données", "data cleaning",
                     "exploration de données", "data mining",
                     "modélisation de données", "data modeling",
                     "manipulation de données", "data wrangling", 
                     "big data",
                     "google analytics",
                     "intelligence d'affaires", "business intelligence",
                     "pensée critique", "critical thinking",
                     "résolution de problèmes",
                     "travail d'équipe",
                     "souci du détail", "attention aux détails", "attention to detail",
                     "gestion du temps", "time management",
                     "gestion de projet", "project management",
                     "prise de décision", 
                     "compétences en présentation", "presentation skills",
                     "bases de données",
                     "google cloud platform", "microsoft azure",
                     "traitement du langage naturel",
                     "sentiment analysis", "analyse de sentiment", "text mining", "topic modeling", "named entity recognition", 
                     "text classification", "text preprocessing",
                     "gestion des données", "data gouvernance",
                     "méthodes agiles"
                     ]