codes = {"paris": 75,
        "saint-ouen-sur-seine": 93,
        "toulouse": 31,
        "la défense": 92,
        "dardilly": 69,
        "lyon": 69,
        "orléans": 45,
        "chasseneuil-du-poitou": 86,
        "le bourget-du-lac": 73,
        "bègles": 33,
        "bordeaux": 33,
        "levallois perret": 92,
        "saint-denis": 93,
        "montrouge": 92,
        "grenoble": 38,
        "l'isle-jourdain": 32
        }
